-- FP-004 — Gestión de mascotas
-- Modelo base: catálogo de especies, mascotas, fotografías y RLS.
-- No incluye reportes ni Storage; se añadirán en migraciones posteriores.

-- ============================================================================
-- Catálogo extensible de especies
-- ============================================================================

create table public.pet_species (
  id smallint generated by default as identity primary key,
  code text not null,
  category text not null,
  sort_order smallint not null default 0,
  is_enabled boolean not null default true,
  mvp_enabled boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),

  constraint pet_species_code_format
    check (code ~ '^[A-Z][A-Z0-9_]{1,49}$'),

  constraint pet_species_category_valid
    check (category in ('COMPANION', 'EQUINE', 'FARM', 'OTHER')),

  constraint pet_species_sort_order_valid
    check (sort_order >= 0)
);

create unique index pet_species_code_unique_idx
  on public.pet_species (code);

create index pet_species_catalog_idx
  on public.pet_species (category, is_enabled, mvp_enabled, sort_order);

create trigger pet_species_set_updated_at
before update on public.pet_species
for each row
execute function public.set_updated_at();

insert into public.pet_species (
  code,
  category,
  sort_order,
  is_enabled,
  mvp_enabled
)
values
  ('DOG', 'COMPANION', 10, true, true),
  ('CAT', 'COMPANION', 20, true, true),
  ('BIRD', 'COMPANION', 30, true, true),
  ('RABBIT', 'COMPANION', 40, true, true),
  ('RODENT', 'COMPANION', 50, true, true),
  ('REPTILE', 'COMPANION', 60, true, true),
  ('OTHER_COMPANION', 'COMPANION', 90, true, true),

  ('FERRET', 'COMPANION', 100, false, false),
  ('TURTLE', 'COMPANION', 110, false, false),
  ('FISH', 'COMPANION', 120, false, false),
  ('AMPHIBIAN', 'COMPANION', 130, false, false),

  ('HORSE', 'EQUINE', 200, false, false),
  ('PONY', 'EQUINE', 210, false, false),
  ('DONKEY', 'EQUINE', 220, false, false),

  ('GOAT', 'FARM', 300, false, false),
  ('SHEEP', 'FARM', 310, false, false),
  ('PIG', 'FARM', 320, false, false),
  ('CATTLE', 'FARM', 330, false, false),
  ('CHICKEN', 'FARM', 340, false, false),
  ('DUCK', 'FARM', 350, false, false),
  ('GOOSE', 'FARM', 360, false, false),
  ('OTHER_FARM', 'FARM', 390, false, false),

  ('OTHER', 'OTHER', 900, false, false);

-- ============================================================================
-- Mascotas
-- ============================================================================

create table public.pets (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete restrict,
  species_id smallint not null references public.pet_species(id) on delete restrict,

  name text not null,
  breed text,
  is_mixed_breed boolean not null default false,
  sex text not null default 'UNKNOWN',
  birth_date date,
  birth_date_precision text not null default 'UNKNOWN',
  size text not null default 'UNKNOWN',
  weight_kg numeric(6, 2),

  primary_color text,
  secondary_colors text[] not null default '{}',
  description text,
  distinctive_features text,

  has_microchip boolean not null default false,
  microchip_number text,
  identification_notes text,
  private_notes text,

  status text not null default 'ACTIVE',
  visibility text not null default 'PUBLIC_WHEN_REPORTED',

  archived_at timestamptz,
  deceased_at date,

  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),

  constraint pets_name_length
    check (char_length(trim(name)) between 1 and 80),

  constraint pets_breed_length
    check (breed is null or char_length(breed) <= 120),

  constraint pets_sex_valid
    check (sex in ('FEMALE', 'MALE', 'UNKNOWN')),

  constraint pets_birth_date_not_future
    check (birth_date is null or birth_date <= current_date),

  constraint pets_birth_date_precision_valid
    check (birth_date_precision in ('EXACT', 'APPROXIMATE', 'UNKNOWN')),

  constraint pets_birth_date_consistency
    check (
      (birth_date is null and birth_date_precision = 'UNKNOWN')
      or
      (birth_date is not null and birth_date_precision in ('EXACT', 'APPROXIMATE'))
    ),

  constraint pets_size_valid
    check (size in ('TINY', 'SMALL', 'MEDIUM', 'LARGE', 'GIANT', 'UNKNOWN')),

  constraint pets_weight_valid
    check (weight_kg is null or (weight_kg > 0 and weight_kg <= 9999.99)),

  constraint pets_primary_color_length
    check (primary_color is null or char_length(primary_color) <= 80),

  constraint pets_secondary_colors_count
    check (cardinality(secondary_colors) <= 8),

  constraint pets_description_length
    check (description is null or char_length(description) <= 1000),

  constraint pets_distinctive_features_length
    check (
      distinctive_features is null
      or char_length(distinctive_features) <= 1000
    ),

  constraint pets_microchip_format
    check (
      microchip_number is null
      or microchip_number ~ '^[A-Z0-9]{8,30}$'
    ),

  constraint pets_microchip_consistency
    check (
      (has_microchip = false and microchip_number is null)
      or
      (has_microchip = true)
    ),

  constraint pets_identification_notes_length
    check (
      identification_notes is null
      or char_length(identification_notes) <= 1000
    ),

  constraint pets_private_notes_length
    check (private_notes is null or char_length(private_notes) <= 2000),

  constraint pets_status_valid
    check (status in ('ACTIVE', 'ARCHIVED', 'DECEASED')),

  constraint pets_visibility_valid
    check (visibility in ('PRIVATE', 'PUBLIC_WHEN_REPORTED', 'PUBLIC')),

  constraint pets_status_dates_consistency
    check (
      (status = 'ACTIVE' and archived_at is null and deceased_at is null)
      or
      (status = 'ARCHIVED' and archived_at is not null and deceased_at is null)
      or
      (status = 'DECEASED' and archived_at is null and deceased_at is not null)
    )
);

create unique index pets_microchip_unique_idx
  on public.pets (microchip_number)
  where microchip_number is not null;

create index pets_owner_status_updated_idx
  on public.pets (owner_id, status, updated_at desc);

create index pets_species_status_idx
  on public.pets (species_id, status);

create trigger pets_set_updated_at
before update on public.pets
for each row
execute function public.set_updated_at();

-- Evita cambiar el responsable mediante una actualización ordinaria.
create or replace function public.prevent_pet_owner_change()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.owner_id is distinct from old.owner_id then
    raise exception 'PET_OWNER_CHANGE_NOT_ALLOWED'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger pets_prevent_owner_change
before update of owner_id on public.pets
for each row
execute function public.prevent_pet_owner_change();

-- ============================================================================
-- Fotografías
-- ============================================================================

create table public.pet_photos (
  id uuid primary key default gen_random_uuid(),
  pet_id uuid not null references public.pets(id) on delete cascade,
  storage_path text not null,
  position smallint not null default 0,
  is_primary boolean not null default false,
  visibility text not null default 'PRIVATE',
  alt_text text,
  mime_type text,
  file_size_bytes integer,
  width integer,
  height integer,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),

  constraint pet_photos_storage_path_length
    check (char_length(storage_path) between 1 and 500),

  constraint pet_photos_position_valid
    check (position >= 0),

  constraint pet_photos_visibility_valid
    check (visibility in ('PRIVATE', 'PUBLIC_PROFILE', 'PUBLIC_REPORT')),

  constraint pet_photos_alt_text_length
    check (alt_text is null or char_length(alt_text) <= 300),

  constraint pet_photos_mime_type_valid
    check (
      mime_type is null
      or mime_type in ('image/jpeg', 'image/png', 'image/webp')
    ),

  constraint pet_photos_file_size_valid
    check (file_size_bytes is null or file_size_bytes > 0),

  constraint pet_photos_width_valid
    check (width is null or width > 0),

  constraint pet_photos_height_valid
    check (height is null or height > 0)
);

create unique index pet_photos_storage_path_unique_idx
  on public.pet_photos (storage_path);

create unique index pet_photos_one_primary_per_pet_idx
  on public.pet_photos (pet_id)
  where is_primary = true;

create index pet_photos_pet_position_idx
  on public.pet_photos (pet_id, position);

create trigger pet_photos_set_updated_at
before update on public.pet_photos
for each row
execute function public.set_updated_at();

-- ============================================================================
-- Row Level Security
-- ============================================================================

alter table public.pet_species enable row level security;
alter table public.pets enable row level security;
alter table public.pet_photos enable row level security;

create policy pet_species_select_enabled
  on public.pet_species
  for select
  to anon, authenticated
  using (is_enabled = true);

create policy pets_select_own
  on public.pets
  for select
  to authenticated
  using ((select auth.uid()) = owner_id);

create policy pets_insert_own
  on public.pets
  for insert
  to authenticated
  with check ((select auth.uid()) = owner_id);

create policy pets_update_own
  on public.pets
  for update
  to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

create policy pet_photos_select_own
  on public.pet_photos
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.pets
      where pets.id = pet_photos.pet_id
        and pets.owner_id = (select auth.uid())
    )
  );

create policy pet_photos_insert_own
  on public.pet_photos
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.pets
      where pets.id = pet_photos.pet_id
        and pets.owner_id = (select auth.uid())
    )
  );

create policy pet_photos_update_own
  on public.pet_photos
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.pets
      where pets.id = pet_photos.pet_id
        and pets.owner_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from public.pets
      where pets.id = pet_photos.pet_id
        and pets.owner_id = (select auth.uid())
    )
  );

create policy pet_photos_delete_own
  on public.pet_photos
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.pets
      where pets.id = pet_photos.pet_id
        and pets.owner_id = (select auth.uid())
    )
  );

-- ============================================================================
-- Permisos
-- ============================================================================

grant select on public.pet_species to anon, authenticated;
grant select, insert, update on public.pets to authenticated;
grant select, insert, update, delete on public.pet_photos to authenticated;

-- No se concede DELETE directo sobre public.pets.
-- La eliminación física, si llega a implementarse, deberá ejecutarse mediante
-- lógica controlada de servidor después de comprobar relaciones e historial.
