-- FP-008 — Catálogo normalizado de razas y cruces
-- Transición compatible con pets.breed como texto legado.

create table public.pet_breeds (
  id integer generated by default as identity primary key,
  species_id smallint not null references public.pet_species(id) on delete restrict,
  code text not null,
  canonical_name text not null,
  aliases text[] not null default '{}',
  sort_order integer not null default 0,
  is_enabled boolean not null default true,
  mvp_enabled boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint pet_breeds_code_format check (code ~ '^[A-Z][A-Z0-9_]{1,79}$'),
  constraint pet_breeds_name_length check (char_length(trim(canonical_name)) between 1 and 120),
  constraint pet_breeds_aliases_count check (cardinality(aliases) <= 20),
  constraint pet_breeds_sort_order_valid check (sort_order >= 0)
);

create unique index pet_breeds_species_code_unique_idx
  on public.pet_breeds (species_id, code);

create unique index pet_breeds_species_name_unique_idx
  on public.pet_breeds (species_id, lower(canonical_name));

create index pet_breeds_catalog_idx
  on public.pet_breeds (species_id, is_enabled, mvp_enabled, sort_order, canonical_name);

create trigger pet_breeds_set_updated_at
before update on public.pet_breeds
for each row execute function public.set_updated_at();

alter table public.pet_breeds enable row level security;

create policy pet_breeds_select_enabled
  on public.pet_breeds
  for select
  to anon, authenticated
  using (is_enabled = true);

grant select on public.pet_breeds to anon, authenticated;

alter table public.pets
  add column breed_knowledge text not null default 'UNKNOWN',
  add column primary_breed_id integer references public.pet_breeds(id) on delete restrict,
  add column secondary_breed_id integer references public.pet_breeds(id) on delete restrict;

alter table public.pets
  add constraint pets_breed_knowledge_valid
    check (breed_knowledge in ('KNOWN', 'UNKNOWN', 'MIXED_UNKNOWN')),
  add constraint pets_distinct_breeds
    check (secondary_breed_id is null or primary_breed_id is distinct from secondary_breed_id),
  add constraint pets_secondary_breed_requires_mixed
    check (secondary_breed_id is null or is_mixed_breed = true),
  add constraint pets_known_breed_consistency
    check (
      (breed_knowledge = 'KNOWN' and primary_breed_id is not null)
      or
      (
        breed_knowledge in ('UNKNOWN', 'MIXED_UNKNOWN')
        and primary_breed_id is null
        and secondary_breed_id is null
      )
    ),
  add constraint pets_mixed_unknown_consistency
    check (breed_knowledge <> 'MIXED_UNKNOWN' or is_mixed_breed = true);

create index pets_primary_breed_idx
  on public.pets (primary_breed_id)
  where primary_breed_id is not null;

create index pets_secondary_breed_idx
  on public.pets (secondary_breed_id)
  where secondary_breed_id is not null;

create or replace function public.validate_pet_breed_species()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_species_id smallint;
begin
  if new.primary_breed_id is not null then
    select species_id into selected_species_id
    from public.pet_breeds
    where id = new.primary_breed_id;

    if selected_species_id is distinct from new.species_id then
      raise exception 'PET_PRIMARY_BREED_SPECIES_MISMATCH'
        using errcode = '23514';
    end if;
  end if;

  if new.secondary_breed_id is not null then
    select species_id into selected_species_id
    from public.pet_breeds
    where id = new.secondary_breed_id;

    if selected_species_id is distinct from new.species_id then
      raise exception 'PET_SECONDARY_BREED_SPECIES_MISMATCH'
        using errcode = '23514';
    end if;
  end if;

  return new;
end;
$$;

create trigger pets_validate_breed_species
before insert or update of species_id, primary_breed_id, secondary_breed_id
on public.pets
for each row execute function public.validate_pet_breed_species();

insert into public.pet_breeds
  (species_id, code, canonical_name, aliases, sort_order, mvp_enabled)
select s.id, v.code, v.name, v.aliases, v.sort_order, true
from public.pet_species s
cross join (
  values
    ('GERMAN_SHEPHERD', 'Pastor alemán', array['pastor aleman','ovejero alemán','german shepherd']::text[], 10),
    ('BELGIAN_SHEPHERD', 'Pastor belga', array['malinois','pastor belga malinois']::text[], 20),
    ('AUSTRALIAN_SHEPHERD', 'Pastor australiano', array['australian shepherd','aussie']::text[], 30),
    ('WHITE_SWISS_SHEPHERD', 'Pastor blanco suizo', array['pastor suizo']::text[], 40),
    ('CATALAN_SHEEPDOG', 'Gos d’atura català', array['pastor catalán','gos datura']::text[], 50),
    ('LABRADOR_RETRIEVER', 'Labrador retriever', array['labrador']::text[], 60),
    ('GOLDEN_RETRIEVER', 'Golden retriever', array['golden']::text[], 70),
    ('BORDER_COLLIE', 'Border collie', array['border']::text[], 80),
    ('POODLE', 'Caniche', array['poodle','caniche toy']::text[], 90),
    ('YORKSHIRE_TERRIER', 'Yorkshire terrier', array['yorkshire','yorkie']::text[], 100),
    ('CHIHUAHUA', 'Chihuahua', array[]::text[], 110),
    ('FRENCH_BULLDOG', 'Bulldog francés', array['bulldog frances','frenchie']::text[], 120),
    ('BEAGLE', 'Beagle', array[]::text[], 130),
    ('BOXER', 'Bóxer', array['boxer']::text[], 140),
    ('ROTTWEILER', 'Rottweiler', array[]::text[], 150),
    ('SIBERIAN_HUSKY', 'Husky siberiano', array['husky']::text[], 160),
    ('POMERANIAN', 'Pomerania', array['spitz enano']::text[], 170),
    ('SPANISH_WATER_DOG', 'Perro de agua español', array['perro de agua']::text[], 180),
    ('SPANISH_GREYHOUND', 'Galgo español', array['galgo']::text[], 190),
    ('PODENCO_IBICENCO', 'Podenco ibicenco', array['podenco']::text[], 200)
) as v(code, name, aliases, sort_order)
where s.code = 'DOG'
on conflict (species_id, code) do nothing;

insert into public.pet_breeds
  (species_id, code, canonical_name, aliases, sort_order, mvp_enabled)
select s.id, v.code, v.name, v.aliases, v.sort_order, true
from public.pet_species s
cross join (
  values
    ('EUROPEAN_SHORTHAIR', 'Europeo de pelo corto', array['gato europeo','común europeo']::text[], 10),
    ('SIAMESE', 'Siamés', array['siames']::text[], 20),
    ('PERSIAN', 'Persa', array[]::text[], 30),
    ('MAINE_COON', 'Maine coon', array[]::text[], 40),
    ('BRITISH_SHORTHAIR', 'British shorthair', array['británico de pelo corto']::text[], 50),
    ('BENGAL', 'Bengalí', array['bengali','bengal']::text[], 60),
    ('RAGDOLL', 'Ragdoll', array[]::text[], 70),
    ('SPHYNX', 'Sphynx', array['esfinge']::text[], 80)
) as v(code, name, aliases, sort_order)
where s.code = 'CAT'
on conflict (species_id, code) do nothing;

-- Las fichas existentes conservan pets.breed y quedan en UNKNOWN.
-- El backfill se hará tras validar catálogo y mapeos.
